import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import {
  useLogoutMutation,
  usePostsQuery,
  useTeamInviteSubscription,
} from "src/generated/graphql";
import Homepage from "src/pages/homepage";
import AuthContext from "src/stores/AuthContext";

const Home: NextPage = () => {
  const [, logout] = useLogoutMutation();
  const [{ data }] = usePostsQuery();
  const [{ data: subcriptions }] = useTeamInviteSubscription();
  const history = useRouter();
  const user = useContext(AuthContext);

  console.info(subcriptions?.teamInvite);
  console.info(user?.id);

  const handleLogout = async () => {
    logout();
    history.reload();
  };

  if (!user) {
    return <Homepage />;
  }

  return (
    <div>
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div
          style={{
            display: "flex",
            width: 200,
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <h3>Hello, {user.username}</h3>
          <button style={{ height: 20 }} onClick={handleLogout}>
            Logout
          </button>
        </div>
        {data?.posts.map((p) => {
          return (
            <div key={p.id}>
              <h3>{p.title}</h3>
              <p>{p.body}</p>
              <p>
                {p.creator.username} - {new Date(p.createdAt).toDateString()}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Home;
