import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { usePostsQuery } from "src/generated/graphql";
import Dashboard from "src/pages/dashboard";
import Homepage from "src/pages/homepage";
import AuthContext from "src/stores/AuthContext";

const Home: NextPage = () => {
  const [{ data }] = usePostsQuery();
  const user = useContext(AuthContext);

  if (!user) {
    return <Homepage />;
  }

  return (
    <div
      style={{
        width: "100vw",
        height: "100vh",
        margin: 0,
        padding: 0,
      }}
    >
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
};

export default Home;
