import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import { useLogoutMutation, usePostsQuery } from "src/generated/graphql";
import AuthContext from "src/stores/AuthContext";

const Home: NextPage = () => {
  const [, logout] = useLogoutMutation();
  const [{ data }] = usePostsQuery();
  const history = useRouter();
  const user = useContext(AuthContext);

  const handleLogout = async () => {
    logout();
    history.reload();
  };

  if (!user) {
    history.push("/login");
    return <></>;
  }

  return (
    <div>
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <a onClick={handleLogout}>Logout</a>
        {data?.posts.map((p) => {
          return (
            <div key={p.id}>
              <h3>{p.title}</h3>
              <p>{p.body}</p>
              <p>
                {p.creator.username} - {new Date(p.createdAt).toDateString()}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Home;
