import type { NextPage } from "next";
import Head from "next/head";
import LoginPage from "src/pages/login";

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </div>
  );
};

export default Login;
