import type { NextPage } from "next";
import Head from "next/head";
import RegisterPage from "src/pages/register";

const Register: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterPage />
    </div>
  );
};

export default Register;
