import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import RegisterPage from "src/pages/register";
import AuthContext from "src/stores/AuthContext";

const Register: NextPage = () => {
  const user = useContext(AuthContext);
  const history = useRouter();

  if (user) {
    history.push("/");
    return <></>;
  }

  return (
    <div>
      <Head>
        <title>Dark Crystal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterPage />
    </div>
  );
};

export default Register;
