version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerasdf
      POSTGRES_USER: postgres
      POSTGRES_DB: darkcrystaldev
    volumes:
      - ../darkcrystaldev/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
